    #application config
app:
    name: kanass
spring:
    profiles:
        active: demo

#web config
server:
    port: 8080

DATA_HOME: /opt/tiklab/tiklab-kanass

jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5010/tiklab_kanass?stringtype=unspecified
    username: postgres
    password: darth2020

#jdbc:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.10.1.10:3306/tiklab_sward?characterEncoding=utf8&useSSL=false
#    username: root
#    password: darth2020

postgresql:
    embbed:
        enable: true
    database: tiklab_kanass
    db:
        port: 5010
        username: postgres
        password: darth2020
        address: ${DATA_HOME}/postgresql

#soular config
auth:
    type: soular
    soular:
        address: http://soular-ce.demoee.tiklab.net

#dfs config
#dfs.service.enabled=false
dfs:
    server:
        enabled: true
        port: 4000
        datapath: ${DATA_HOME}/files
    client:
        url: 127.0.0.1:4000
        group: g1
        bucket: kanass

dcs:
    server:
        enabled: true
        port: 6000
        datapath: ${DATA_HOME}/caches
    client:
        url: 127.0.0.1:6000
        group: g1
        database: dcs1
        expire: 7200


external:
    url: http://kanass-ce.demoee.tiklab.net

version:
    check: dGlrbGFidGlrbGFi