    #application config
app:
    name: kanass
spring:
    profiles:
        active: demo

#web config
server:
    port: 8080

DATA_HOME: /opt/tiklab/tiklab-kanass

jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5010/tiklab_kanass?stringtype=unspecified
    username: postgres
    password: darth2020

postgresql:
    embbed:
        enable: true
    database: tiklab_kanass
    db:
        port: 5010
        username: postgres
        password: darth2020
        address: ${DATA_HOME}/postgresql

#soular config
soular:
    embbed:
        enable: false
    address: http://soular-ce.demoee.tiklab.net
#dfs config
#dfs.service.enabled=false
dfs:
    server:
        enabled: true
        port: 4000
        datapath: ${DATA_HOME}/files
    client:
        url: 127.0.0.1:4000
        group: g1
        bucket: kanass

dcs:
    server:
        enabled: true
        port: 6000
        datapath: ${DATA_HOME}/caches
    client:
        url: 127.0.0.1:6000
        group: g1
        database: dcs1
        expire: 7200

#license
licences:
    path: ${APP_HOME}/licences

base:
    url: http://kanass-ce.demoee.tiklab.net

backups:
    time: 0 0 2 * * ?
    dir: /data/kanass
    dfs:
        dir: ${DATA_HOME}/files

#zip config
unzip:
    path: ${DATA_HOME}/unzip/Jira
