CREATE TABLE pmc_version_burndowm(
        id VARCHAR(12) NOT NULL PRIMARY KEY,
        version_id VARCHAR(12) NOT NULL,
        record_time timestamp,
        remain_workitem_count int,
        total_workitem_count int,
        end_workitem_count int,
        progress_workitem_count int,
        nostart_workitem_count int,
        remain_bug_count int,
        total_bug_count int,
        end_bug_count int,
        progress_bug_count int,
        nostart_bug_count int,
        remain_demand_count int,
        total_demand_count int,
        end_demand_count int,
        progress_demand_count int,
        nostart_demand_count int,
        remain_task_count int,
        total_task_count int,
        end_task_count int,
        progress_task_count int,
        nostart_task_count int
);