    #application config
app:
    name: thoughtware-kanass-ce
spring:
    profiles:
        active: demoee

#web config
server:
    port: 8080

DATA_HOME: /opt/thoughtware/kanass-ce

base:
    url: http://kanass-ce.demoee.thoughtware.cn

jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5010/kanass?stringtype=unspecified
    username: postgres
    password: darth2020

postgresql:
    embbed:
        enable: true
    database: kanass
    db:
        port: 5010
        username: postgres
        password: darth2020
        address: ${DATA_HOME}/postgresql

#eas config
eas:
    embbed:
        enable: false
    address: http://eas-ce.demoee.thoughtware.cn
#dfs config
#dfs.server.enabled=false
dfs:
    server:
        enabled: true
        port: 4000
        datapath: ${DATA_HOME}/files
    client:
        url: 127.0.0.1:4000
        group: g1
        bucket: kanass

dcs:
    server:
        enabled: true
        port: 6000
        datapath: ${DATA_HOME}/caches
    client:
        url: 127.0.0.1:6000
        group: g1
        database: dcs1
        expire: 7200
#integration config

homes:
    address: http://192.168.10.6:8070

file:
    path: http://file.dev.kanass.io



#license
licences:
    path: ${APP_HOME}/licences

#plugin config
plugin:
    path: ${DATA_HOME}/plugin

#zip config
unzip:
    path: ${DATA_HOME}/unzip/Jire

client: web
version: ce

backups:
    time: 0 0 2 * * ?
    dir: /data/kanass
    dfs:
        dir: ${DATA_HOME}/files