#系统名称
app:
  name: kanass
# 环境
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB     #单个文件最大限制
      max-request-size: 50MB  #多个文件最大限制

#端口
server:
  port: 8080

DATA_HOME: ${user.home}/tiklab/tiklab-kanass

#db
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_kanass?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: false
  database: tiklab_kanass
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


#dfs config
dfs:
  server:
    enabled: true
    port: 4001
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4001
    group: g1
    bucket: kanass

#dcs config
dcs:
  server:
    enabled: true
    port: 5001
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5001
    group: g1
    database: dcs1
    expire: 7200

soular:
  embbed:
    enable: true
  web:
    address: http://192.168.10.16:3010
  address: http://192.168.10.15:8080


#证书文件路径
licences:
  path: ${APP_HOME}/licences

# 访问地址，用于显示日志，消息，待办的图标
base:
  url: http://192.168.10.7:8080

backups:
  pgsql:
    dir: /opt/homebrew/opt/postgresql@15/bin
  time: 0 0 2 * * ?
  dir: ${DATA_HOME}
  dfs:
    dir: ${DATA_HOME}/files

#zip config
unzip:
  path: ${DATA_HOME}/unzip/Jira

postin:
  scan:
    package: io.tiklab.kanass