#系统名称
app:
  name: kanass
# 环境
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB     #单个文件最大限制
      max-request-size: 50MB  #多个文件最大限制

#端口
server:
  port: 8080

DATA_HOME: ${user.home}/tiklab/tiklab-kanass

#db
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_kanass_test?stringtype=unspecified
  username: postgres
  password: darth2020

#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://172.10.1.10:3306/tiklab_kanass?characterEncoding=utf8&useSSL=false
#  username: root
#  password: darth2020

postgresql:
  embbed:
    enable: false
  database: tiklab_kanass_test
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql


#dfs config分布式
dfs:
  server:
    enabled: true
    port: 4010
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4010
    group: g1
    bucket: kanass

#dcs config分布式缓存
dcs:
  server:
    enabled: true
    port: 5010
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5010
    group: g1
    database: dcs1
    expire: 7200

auth:
  type: local
  soular:
    address: http://192.168.10.15:8080
    web:
      address: http://192.168.10.16:3010

# 访问地址，用于显示日志，消息，待办的图标
external:
  url: http://192.168.10.7:8080

backups:
  pgsql:
    dir: /opt/homebrew/opt/postgresql@15/bin
  time: 0 0 2 * * ?
  dir: ${DATA_HOME}
  dfs:
    dir: ${DATA_HOME}/files

#zip config
unzip:
  jiraPath: ${DATA_HOME}/unzip/Jira
  # jira附件在压缩包中的位置
  jiraAttachment: ${unzip.jiraPath}/attachments
  mantisPath: ${DATA_HOME}/unzip/Mantis
  mantisAttachment: ${unzip.mantisPath}/attachments
