#系统名称
app:
    name: kanass
spring:
    profiles:
        active: dev
    config:
        import: optional:classpath:/config/${env:dev}/application.yaml

#web config
server:
    port: 8080

#mac、linux
DATA_HOME: /opt/tiklab/tiklab-kanass

jdbc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.10.1.10:3306/tiklab_kanass?characterEncoding=utf8&useSSL=false
    username: root
    password: darth2020
#jdbc:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:8000/tiklab_kanass?stringtype=unspecified
#    username: postgres
#    password: darth2020

postgresql:
    embbed:
        enable: false
    database: kanass
    db:
        port: 8000
        username: postgres
        password: darth2020
        address: ${DATA_HOME}/postgresql

#soular config
soular:
    embbed:
        enable: true
    address: http://soular-ce.test.kanass.net

#dfs config
#dfs.service.enabled=false
dfs:
    server:
        enabled: true
        port: 4000
        datapath: ${DATA_HOME}/files
    client:
        url: 127.0.0.1:4000
        group: g1
        bucket: kanass

#dcs config
#dcs.service.enabled=false
dcs:
    server:
        enabled: true
        port: 6000
        datapath: ${DATA_HOME}/caches
    client:
        url: 127.0.0.1:6000
        group: g1
        database: dcs1
        expire: 7200

#license
licences:
    path: ${APP_HOME}/src/main/resources/licences

base:
    url: http://kanass-ce.test.kanass.net

backups:
    time: 0 0 2 * * ?
    dir: /data/kanass

#zip config
unzip:
    jiraPath: ${DATA_HOME}/unzip/Jira
    # jira附件在压缩包中的位置
    jiraAttachment: ${unzip.jiraPath}/attachments
    mantisPath: ${DATA_HOME}/unzip/Mantis
    mantisAttachment: ${unzip.mantisPath}/attachments

postin:
    scan:
        package: io.tiklab.kanass
