#系统名称
app:
  name: tiklab-teamwire

# 环境
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB     #单个文件最大限制
      max-request-size: 50MB  #多个文件最大限制

#端口
server:
  port: 8080


jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_teamwire?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  type: local
  embbed:
    enable: false
  database: tiklab_teamwire

# 访问地址，用于显示日志，消息，待办的图标
base:
  url: http://192.168.10.25:8080


DATA_HOME: ${user.home}/tiklab/teamwire

#dfs config
dfs:
  server:
    enabled: true
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    group: g1
    bucket: teamwire

#dcs config
dcs:
  server:
    enabled: true
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    group: g1
    database: dcs1
    expire: 7200
#address: http://eas.local.tiklab.net
#  address: http://eas.dev.tiklab.net
eas:
  embbed:
    enable: true
  web:
    address: http://192.168.10.25:3010
  address: http://192.168.10.6:8080

# homes 地址
#homes:
#  address: http://192.168.10.25:8080

#plugin config
plugin:
  path: ${DATA_HOME}/plugin

#zip config
unzip:
  path: ${DATA_HOME}/unzip/Jire

#证书文件路径
licences:
  path: ${APP_HOME}/licences

client: web
version: ce

homes:
  address: http://192.168.10.6:8070

file:
  path: http://file.dev.tiklab.io

user:
  home: ${user.home}

postin:
  enable: false
  scan:
    package: io.tiklab
  report:
    workspaceId: b4a2fc3a3d73
    server: http://192.168.10.3:8090

backups:
  time: 0 0 2 * * ?
  dir: /data/teamwire
