#系统名称

app:
    name: thoughtware-kanass
spring:
    profiles:
        active: release
    config:
        import: optional:classpath:/config/${env:dev}/application.yaml

#web config
server:
    port: 8080


base:
    url: http://kanass-ce.kanass.net

jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8000/kanass?stringtype=unspecified
    username: postgres
    password: darth2020

postgresql:
    embbed:
        enable: true
    database: kanass
    db:
        port: 8000
        username: postgres
        password: darth2020
        address: ${DATA_HOME}/postgresql

#eas config
eas:
    embbed:
        enable: true

DATA_HOME: /Users/yuanjiexuan/thoughtware1/kanass
#dfs config
#dfs.server.enabled=false
dfs:
    server:
        enabled: true
        port: 4000
        datapath: ${DATA_HOME}/files
    client:
        url: 127.0.0.1:4000
        group: g1
        bucket: kanass

#dcs config
dcs:
    server:
        enabled: true
        port: 5000
        datapath: ${DATA_HOME}/caches
    client:
        url: 127.0.0.1:5000
        group: g1
        database: dcs1
        expire: 7200

licences:
    path: ${APP_HOME}/src/main/resources/licences
#integration config

plugin:
    path: ${APP_HOME}/plugin

homes:
    address: http://192.168.10.6:8070

file:
    path: http://file.dev.kanass.io


#zip config
unzip:
    path: ${DATA_HOME}/unzip/Jire

client: web
version: ce

backups:
    time: 0 0 2 * * ?
    dir: /data/kanass
