#系统名称

app:
    name: thoughtware-kanass
spring:
    profiles:
        active: release
    config:
        import: optional:classpath:/config/${env:dev}/application.yaml

#web config
server:
    port: 8080

#mac、linux
DATA_HOME: /opt/thoughtware/kanass-ce


base:
    url: http://kanass-ce.test.kanass.net

jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8000/kanass?stringtype=unspecified
    username: postgres
    password: darth2020

postgresql:
    embbed:
        enable: true
    database: kanass
    db:
        port: 8000
        username: postgres
        password: darth2020
        address: ${DATA_HOME}/postgresql


#soular config
soular:
    embbed:
        enable: true
    address: http://soular-ce.test.kanass.net
#dfs config
#dfs.server.enabled=false
dfs:
    server:
        enabled: true
        port: 4000
        datapath: ${DATA_HOME}/files
    client:
        url: 127.0.0.1:4000
        group: g1
        bucket: kanass

#dcs config
#dcs.server.enabled=false
dcs:
    server:
        enabled: true
        port: 6000
        datapath: ${DATA_HOME}/caches
    client:
        url: 127.0.0.1:6000
        group: g1
        database: dcs1
        expire: 7200

#license
licences:
    path: ${APP_HOME}/src/main/resources/licences

#plugin config
plugin:
    path: ${DATA_HOME}/plugin

#zip config
unzip:
    path: ${DATA_HOME}/unzip/Jire

homes:
    address: http://192.168.10.6:8070

file:
    path: http://file.dev.kanass.io


client: web
version: ce

backups:
    time: 0 0 2 * * ?
    dir: /data/kanass