CREATE TABLE pmc_project_set_burndowm (
                                          id VARCHAR(12) NOT NULL PRIMARY KEY,
                                          project_set_id VARCHAR(12) NOT NULL,
                                          record_time TIMESTAMP NULL DEFAULT NULL,
                                          remain_workitem_count INT DEFAULT NULL,
                                          total_workitem_count INT DEFAULT NULL,
                                          end_workitem_count INT DEFAULT NULL,
                                          progress_workitem_count INT DEFAULT NULL,
                                          nostart_workitem_count INT DEFAULT NULL,
                                          remain_bug_count INT DEFAULT NULL,
                                          total_bug_count INT DEFAULT NULL,
                                          end_bug_count INT DEFAULT NULL,
                                          progress_bug_count INT DEFAULT NULL,
                                          nostart_bug_count INT DEFAULT NULL,
                                          remain_demand_count INT DEFAULT NULL,
                                          total_demand_count INT DEFAULT NULL,
                                          end_demand_count INT DEFAULT NULL,
                                          progress_demand_count INT DEFAULT NULL,
                                          nostart_demand_count INT DEFAULT NULL,
                                          remain_task_count INT DEFAULT NULL,
                                          total_task_count INT DEFAULT NULL,
                                          end_task_count INT DEFAULT NULL,
                                          progress_task_count INT DEFAULT NULL,
                                          nostart_task_count INT DEFAULT NULL,
                                          INDEX idx_project_set_id (project_set_id),
                                          INDEX idx_record_time (record_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;